require:
  - rubocop
  - rubocop-rails
  - rubocop-rspec

AllCops:
  NewCops: enable
  DisplayCopNames: true
  DisplayStyleGuide: true
  TargetRubyVersion: 2.7
  Exclude:
    - bin/**/*
    - config/**/*
    - db/**/*
    - log/**/*
    - public/**/*
    - tmp/**/*
    - Rakefile
    - node_modules/**/*
    - vendor/bundle/**/*
RSpec:
  Include:
    - '^spec.*\*\.rb'
Metrics/MethodLength:
  Max: 40
Metrics/AbcSize:
  Max: 30
Security/Eval:
  Enabled: false
Style/Documentation:
  Enabled: false
Metrics/BlockLength:
  Exclude:
    - 'config/routes.rb'
    - 'spec/**/*.rb'
Rails/FilePath:
  Enabled: false